name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  set-version:
    name: Set's the version on 'Cargo.toml'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get latest release version number
      id: get_version
      uses: battila7/get-version-action@v2
    - name: Bump crate version
      uses: thomaseizinger/set-crate-version@master
      with:
        version: ${{ steps.get_version.outputs.version }}
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Cargo update
      uses: actions-rs/cargo@v1
      with:
        command: update
    - name: Commit the new version
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Set Cargo.toml to the right version'
        files: Cargo.toml Cargo.lock
        name: ${{ github.event.pusher.name }}
        email: ${{ github.event.pusher.email }}

  publish-github:
    name: Publish to GitHub release for ${{ matrix.os }}
    needs: set-version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: docked
            asset_name: docked-linux-amd64
          - os: windows-latest
            artifact_name: docked.exe
            asset_name: docked-windows-amd64.exe
          - os: macos-latest
            artifact_name: docked
            asset_name: docked-macos-amd64

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}

  publish-crates:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: set-version
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Login Cargo
      uses: actions-rs/cargo@v1
      with:
        command: login
        args: ${{ secrets.CRATES_API_TOKEN }}
    - name: Publish
      uses: actions-rs/cargo@v1
      with:
        command: publish

